[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gpx-openmap"
dynamic = ["version"]
description = "Analyse and display your gps tracks on a map."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "Fred C.", email = "github-fred@hidzz.com" }
]
keywords = ["ham radio", "wspr", "antenna"]
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: BSD License",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "folium",
    "gpxpy",
    "matplotlib",
    "numpy",
    "pandas",
    "tzlocal",
    "pyproj",
    "simplekml",
]

[project.urls]
Homepage = "https://github.com/0x9900/gpxmap"
Repository = "https://github.com/0x9900/gpxmap"

[project.scripts]
gpxmap = "gpxmap.gpxmap:main"

[tool.hatch.build.targets.wheel]
packages = ["src/gpxmap"]

[tool.hatch.version]
path = "src/gpxmap/__init__.py"

[project.optional-dependencies]
dev = [
    "build",
    "flake8",
    "geo_ham",
    "isort",
    "mypy",
    "pre-commit",
    "pylint",
    "twine",
]

[tool.mypy]
ignore_missing_imports = true
